export class Config implements IDrawflowConfig {
  constructor(
    public container: Container,
    public events = {},
    public precanvas = null,
    public nodeId = 1,
    public ele_selected = null,
    public node_selected = null,
    public drag = false,
    public reroute = false,
    public reroute_fix_curvature = false,
    public curvature = 0.5,
    public reroute_curvature_start_end = 0.5,
    public reroute_curvature = 0.5,
    public reroute_width = 6,
    public drag_point = false,
    public editor_selected = false,
    public connection = false,
    public connection_ele = null,
    public connection_selected = null,
    public canvas_x = 0,
    public canvas_y = 0,
    public pos_x = 0,
    public pos_x_start = 0,
    public pos_y = 0,
    public pos_y_start = 0,
    public mouse_x = 0,
    public mouse_y = 0,
    public line_path = 5,
    public first_click = null,
    public force_first_input = false,
    public draggable_inputs = true,
    public useuuid = false,
    public noderegister = {},
    public drawflow = { "drawflow": { "Home": { "data": {} }}},
    public evCache = [],
    public prevDiff = -1
  ) {
  }
}
